# Generated by Django 3.1.2 on 2020-11-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_empleado_employee_userparent_viewcat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewcat',
            options={'managed': False},
        ),
    ]
